### ISSUE TITLE
只有【Use ai digest】的情况下 无法进行ai总结。会提示出错

### ISSUE THREAD

**Issue by Whichbfj28** [yinan-c/RSSbrew#12]
![image](https://github.com/user-attachments/assets/a57e7015-d724-4045-b108-420cebc637a2)

`GenerateContentRequest.contents[2].parts[0].data: required oneof field 'data' must have one initialized field`
gpt输出错误日志。

**Comment by yinan-c** [comment]
感谢提 bug，因为之前不小心设置成了把 digest 文章发给 AI 总结，当这些全都不选的时候，相当于发给 AI 空白内容，现在应该已经在 b20f732 修复
