### ISSUE TITLE
【取消缩进】取消ai总结缩进。在手机小屏幕上不友好

### ISSUE THREAD

**Issue by Whichbfj28** [yinan-c/RSSbrew#13]
![image](https://github.com/user-attachments/assets/e4120c7b-9afd-45ee-b3b1-fa6b2630f578)
【取消缩进】取消ai总结缩进。在手机小屏幕上不友好。手机上本来没多大。缩进后会留下一大堆空白。

**Comment by yinan-c** [comment]
感谢 PR
