### ISSUE TITLE
Add support for env variables for redis host and port. 

### ISSUE THREAD

**Issue by jolpadgett** [yinan-c/RSSbrew#16]
The hardcoded redis hostname and port makes it difficult to host alongside other containers sharing the same network, some of which need their own independent redis. 

Allowing this to be set via env variables provides flexibility. 

Bonus: allow setting redis connect string with database index so one redis instance can be shared would also be helpful.

**Comment by yinan-c** [comment]
Hi, will consider modify the hard coded part in the next update, soon

**Comment by yinan-c** [comment]
Hi, could you please check out commit [216c26a](https://github.com/yinan-c/RSSbrew/commit/216c26a531f338383bdf3195bc9f3babc05ef21f) to see if this is what you meant? Feel free to leave any more suggestions.
